version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: New@01234
      POSTGRES_DB: portfolio_db
    ports:
      - "5433:5432"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:New@01234@db:5432/portfolio_db

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
