version: '3'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - client
